#!/bin/bash
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# System Request : Debian 9+/Ubuntu 18.04+/20+
# Develovers » FanVPN-Store
# Email      » HurufKapital58@gmail.com
# telegram   » https://t.me/AJW29
# whatsapp   » wa.me/+6287812264674
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# FanVPN-Store

clear
y='\033[1;33m'
BGX="\033[42m"
CYAN="\033[0;36m"
z="\033[95;1m"
f="\033[1;97;41m"
G="\033[92m"
RED='\033[1;31m'
BRED='\033[1;31m'
NC='\033[0m'
gray="\e[1;30m"
UNGU="\033[1;35m"
Blue="\033[1;34m"
bblue="\033[1;34m"
green='\033[0;32m'
GREEN='\033[1;32m'
grenbo="\e[92;1m"
pr="\033[0;95m"
YELL='\033[1;93m'
orange='\033[33m'
mg='\033[35m'
white='\033[1;97m'
bwhite='\033[1;37m'

# underline
UPU='\033[5;35m'
UCY='\033[5;36m'
UWH='\033[5;37m'
# INTALLER-UDP
UDPX="https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1S3IE25v_fyUfCLslnujFBSBMNunDHDk2' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1S3IE25v_fyUfCLslnujFBSBMNunDHDk2"
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
IPVPS=$(curl -s ipv4.icanhazip.com)
domain=$(cat /etc/xray/domain)
RAM=$(free -m | awk 'NR==2 {print $2}')
USAGERAM=$(free -m | awk 'NR==2 {print $3}')
MEMOFREE=$(printf '%-1s' "$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')")
LOADCPU=$(printf '%-0.00001s' "$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')")
MODEL=$(cat /etc/os-release | grep -w PRETTY_NAME | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/PRETTY_NAME//g')
CORE=$(printf '%-1s' "$(grep -c cpu[0-9] /proc/stat)")
DATEVPS=$(date +'%d-%m-%Y')
TIMEZONE=$(printf '%(%H-%M-%S)T')
SERONLINE=$(uptime -p | cut -d " " -f 2-10000)
clear
MYIP=$(curl -sS ipv4.icanhazip.com)
echo ""
izinsc="https://raw.githubusercontent.com/Pemulaajiw/script/main/register"
# USERNAME
rm -f /usr/bin/user
username=$(curl ${izinsc} | grep $MYIP | awk '{print $2}')
echo "$username" >/usr/bin/user
# validity
rm -f /usr/bin/e
valid=$(curl ${izinsc} | grep $MYIP | awk '{print $3}')
echo "$valid" >/usr/bin/e
# DETAIL ORDER
username=$(cat /usr/bin/user)
oid=$(cat /usr/bin/ver)
exp=$(cat /usr/bin/e)
clear
# CERTIFICATE STATUS
d1=$(date -d "$valid" +%s)
d2=$(date -d "$today" +%s)
certifacate=$(((d1 - d2) / 86400))
# VPS Information
DATE=$(date +'%Y-%m-%d')
datediff() {
    d1=$(date -d "$1" +%s)
    d2=$(date -d "$2" +%s)
    echo -e "$COLOR1 $NC Expiry In   : $(( (d1 - d2) / 86400 )) Days"
}
mai="datediff "$Exp" "$DATE""

# Status Expired Or Active
Info="(${green}Active${NC})"
Error="(${RED}Expired${NC})"
today=`date -d "0 days" +"%Y-%m-%d"`
Exp1=$(curl ${izinsc} | grep $MYIP | awk '{print $3}')
if [[ $today < $Exp1 ]]; then
sts="${Info}"
else
sts="${Error}"
fi
clear

# OS Uptime
uptime="$(uptime -p | cut -d " " -f 2-10)"

# Getting CPU Information
cpu_usage1="$(ps aux | awk 'BEGIN {sum=0} {sum+=$3}; END {print sum}')"
cpu_usage="$((${cpu_usage1/\.*} / ${coREDiilik:-1}))"
cpu_usage+=" %"
ISP=$(curl -s ipinfo.io/org | cut -d " " -f 2-10 )
CITY=$(curl -s ipinfo.io/city )
WKT=$(curl -s ipinfo.io/timezone )
DAY=$(date +%A)
DATE=$(date +%m/%d/%Y)
DATE2=$(date -R | cut -d " " -f -5)

# IPVPS=$(curl -s ipinfo.io/ip )
IPVPS=$(curl -sS ipv4.icanhazip.com) 
cname=$( awk -F: '/model name/ {name=$2} END {print name}' /proc/cpuinfo )
cores=$( awk -F: '/model name/ {core++} END {print core}' /proc/cpuinfo )
freq=$( awk -F: ' /cpu MHz/ {freq=$2} END {print freq}' /proc/cpuinfo )
tram=$( free -m | awk 'NR==2 {print $2}' )
uram=$( free -m | awk 'NR==2 {print $3}' )
fram=$( free -m | awk 'NR==2 {print $4}' )
clear
ssh_service=$(/etc/init.d/ssh status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
dropbear_service=$(/etc/init.d/dropbear status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
haproxy_service=$(systemctl status haproxy | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
xray_service=$(systemctl status xray | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
nginx_service=$(systemctl status nginx | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
#Status
clear
# STATUS SERVICE  SSH 
if [[ $ssh_service == "running" ]]; then 
   status_ssh="${GREEN}ON${NC}"
else
   status_ssh="${RED}OFF${NC}"
fi

# SSH Websocket Proxy
ssh_ws=$( systemctl status ws | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
if [[ $ssh_ws == "running" ]]; then
    status_ws_epro="${GREEN}ON${NC}"
else
    status_ws_epro="${RED}OFF${NC}"
fi

# STATUS SERVICE HAPROXY
if [[ $haproxy_service == "running" ]]; then 
   status_haproxy="${GREEN}ON${NC}"
else
   status_haproxy="${RED}OFF${NC}"
fi

# STATUS SERVICE XRAY
if [[ $xray_service == "running" ]]; then 
   status_xray="${GREEN}ON${NC}"
else
   status_xray="${RED}OFF${NC}"
fi

# STATUS SERVICE NGINX
if [[ $nginx_service == "running" ]]; then 
   status_nginx="${GREEN}ON${NC}"
else
   status_nginx="${RED}OFF${NC}"
fi

# STATUS SERVICE Dropbear
if [[ $dropbear_service == "running" ]]; then 
   status_dropbear="${GREEN}ON${NC}"
else
   status_dropbear="${RED}OFF${NC}"
fi

# // Log account
vlx=$(grep -c -E "^#& " "/etc/xray/config.json")
let vla=$vlx/2
vmc=$(grep -c -E "^### " "/etc/xray/config.json")
let vma=$vmc/2
ssh1="$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
trx=$(grep -c -E "^#! " "/etc/xray/config.json")
let trb=$trx/2
ssx=$(grep -c -E "^#ss# " "/etc/xray/config.json")
let ssa=$ssx/2

a="ACCOUNT PREMIUM" 
KANAN="\033[1;32m<\033[1;33m<\033[1;31m<\033[1;31m${NC}"
KIRI="\033[1;32m>\033[1;33m>\033[1;31m>\033[1;31m${NC}"
                        
BICyan='\033[1;36m'       # Cyan
BIWhite='\033[1;97m'      # White
UWhite='\033[4;37m'       # White
BIYellow='\033[1;93m'     # Yellow

clear
echo -e "${RED} ┌─────────────────────────────────────────────────────┐${NC}"
echo -e "${RED} │                   ${BIWhite}${UWhite}FAN VPN STORE${NC}"
echo -e "${RED} └─────────────────────────────────────────────────────┘${NC}"
echo -e "${RED} ┌─────────────────────────────────────────────────────┐${NC}"
echo -e "${RED} │  ${RED}SYSTEM VPS  : ${white}$MODEL${NC}"
echo -e "${RED} │  ${RED}ISP VPS     : ${YELL}$ISP${NC}"
echo -e "${RED} │  ${RED}CITY        : ${YELL}$CITY${NC}"
echo -e "${RED} │  ${RED}RAM SERVER  : ${white}$uram / $tram MB ${NC}"
echo -e "${RED} │  ${RED}DATE VPS    : ${white}$DATEVPS${NC}"
echo -e "${RED} │  ${RED}IP SERVER   : ${GREEN}$IPVPS${NC}"
echo -e "${RED} │  ${RED}DOMAIN VPS  : ${GREEN}$domain${NC}"
echo -e "${RED} │  ${RED}TIMEZONE    : ${white}$TIMEZONE${NC}"
echo -e "${RED} │  ${RED}UPTIME VPS  : ${white}$SERONLINE${NC}"
echo -e "${RED} └─────────────────────────────────────────────────────┘${NC}"
echo -e " ${NC}   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"| lolcat
echo -e " ${NC}              ${KIRI} INFORMATION ACCOUNT ${KANAN}"
echo -e " ${NC}   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}" | lolcat
echo -e "         ${RED} SSH/OPENVPN/UDP  $white:$NC $ssh1  ${BIWhite}$a"
echo -e "         ${RED} VMESS/WS/GRPC    $white:$NC $vma  ${BIWhite}$a"
echo -e "         ${RED} VLESS/WS/GRPC    $white:$NC $vla  ${BIWhite}$a"
echo -e "         ${RED} TROJAN/WS/GRPC   $white:$NC $trb  ${BIWhite}$a"
echo -e "         ${RED} SHADOW/WS/GRPC   $white:$NC $ssa  ${BIWhite}$a"
echo -e " ${NC}   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}" | lolcat
echo -e " ${NC}      ${KIRI} MENU AUTOSCRIPT By FAN VPN STORE  ${KANAN}"
echo -e " ${z}╭════════════════╮╭══════════════════╮╭════════════════════╮${NC}"
echo -e " ${RED}│ ${NC}$z SSH$NC : $status_ssh" "       $z NGINX$NC : $status_nginx" "       $z XRAY$NC : $status_xray     $NC${RED}│$NC" 
echo -e " ${RED}│ ${NC}$z WS-ePRO$NC : $status_ws_epro" "   $z DROPBEAR$NC : $status_dropbear" "    $z HAPROXY$NC : $status_haproxy  $NC${RED}│$NC" 
echo -e " ${z}╰════════════════╯╰══════════════════╯╰════════════════════╯${NC}" lolcat
echo -e "${RED} ┌─────────────────────────────────────────────────────┐${NC}"
echo -e "${RED} │  ${RED}[${BIWhite}01${RED}] SSH     ${RED}[${BIWhite}Menu${RED}]${NC}"  "${RED}  [${BIWhite}05${RED}] SHADOW     ${RED}[${BIWhite}Menu${RED}]${NC}" "${RED} │${NC}"
echo -e "${RED} │  ${RED}[${BIWhite}02${RED}] VMESS   ${RED}[${BIWhite}Menu${RED}]${NC}"  "${RED}  [${BIWhite}06${RED}] NOOBZVPN   ${RED}[${BIWhite}Menu${RED}]${NC}" "${RED} │${NC}"
echo -e "${RED} │  ${RED}[${BIWhite}03${RED}] VLESS   ${RED}[${BIWhite}Menu${RED}]${NC}"  "${RED}  [${BIWhite}07${RED}] BOT VIP    ${RED}[${BIWhite}Menu${RED}]${NC}" "${RED} │${NC}"
echo -e "${RED} │  ${RED}[${BIWhite}04${RED}] TROJAN  ${RED}[${BIWhite}Menu${RED}]${NC}"  "${RED}  [${BIWhite}08${RED}] THEMES     ${RED}[${BIWhite}Menu${RED}]${NC}" "${RED} │${NC}"
echo -e "${RED} │  ${RED}[${BIWhite}09${RED}] SYSTEM  ${RED}[${BIWhite}Menu${RED}]${NC}"  "${RED}  [${BIWhite}10${RED}] UPDATE     ${RED}[${BIWhite}Menu${RED}]${NC}" "${RED} │${NC}"
echo -e "${RED} └─────────────────────────────────────────────────────┘${NC}"
echo -e " ${RED}       ${KIRI} *JANGAN LUPA SHOLAT GUYS*📴  ${KANAN}" | lolcat
echo -e "${RED}    0ཻུ۪۪ꦽꦼ̷⸙‹•══════════════════════════════════════════════♡᭄${NC}"
echo -e "${RED}    │  ${RED}Script Version :${Blue} 2.4 ${YELL}[${BIWhite}Last Update${Blue}]${NC}"
echo -e "${RED}    │  ${RED}Script Status  :${NC} $sts"
echo -e "${RED}    │  ${RED}Username       :${Blue} $username${NC}"
echo -e "${RED}    │  ${RED}Expired script :${RED} $exp ${RED}[${BIWhite}$certifacate Days${RED}]${NC}"
echo -e "${RED}    0ཻུ۪۪ꦽꦼ̷⸙‹•══════════════════════════════════════════════♡᭄${NC}"
echo -e " "
read -p "  Select From Options [ 1-10 ] »» " opt

case $opt in
1 | 01)
clear
m-sshws
;;
2 | 02)
clear
m-vmess
;;
3 | 03)
clear
m-vless
;;
4 | 04)
clear
m-trojan
;;
5 | 05)
clear
m-ssws
;;
6 | 06)
clear
m-noob
;;
7 | 07)
clear
m-bot
;;
8 | 08)
clear
m-themes
;;
9 | 09)
clear
m-system;
;;
10)
clear
wget -q https://raw.githubusercontent.com/Pemulaajiw/script/main/update.sh
chmod +x update.sh
./update.sh
;;
0 | 00)
exit
;;
x)
menu
;;
*) clear ;
echo -e ""
menu
;;
esac


